name: ml-experiment-stack
services:
  gpu-jupyter:
    # Jupyter Notebook with most useful libraries installed.
    # Doc: https://github.com/iot-salzburg/gpu-jupyter
    container_name: jupyter_env
    build: jupyter_notebook/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 8888:8888 # Jupyter notebook UI
      - 6006:6006 # Tensorboard UI
    volumes:
      # workspace dir is meant for all files for Jupyter notebook
      - ~/data/experiments/workspace:/home/jovyan/workspace
      # central logs dir meant for global Tensorboard instance
      # - ~/data/experiments/logs:/home/jovyan/logs
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      NB_UID: 1000:1000
      NB_GID: 1000:1000
    # Set user and group to 1000 so it's the same as host.
    # This is needed so that files created in docker will be owned by the same user
    # inside and outside of Docker.
    user: 1000:1000
    restart: always
