name: ml-experiment-stack
services:
  # Jupyter Notebook with most useful libraries installed.
  # Doc: https://github.com/iot-salzburg/gpu-jupyter
  #
  # Ports mapping:
  # - 8080: Jupyter notebook UI
  # - 8081: Tensorboard UI
  gpu-jupyter:
    container_name: jupyter_env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 8080:8888
      - 8081:6006
    volumes:
      - ~/data/ml_notebook:/home/jovyan
    environment:
      - GRANT_SUDO: "yes"
      - JUPYTER_ENABLE_LAB: "yes"
      - NB_UID: ${JUPYTER_UID:-1000}
      - NB_GID: ${JUPYTER_GID:-1000}
      - JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    # for sudo permissions
    user: root
    restart: always
    image: cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04
    command: tensorboard --logdir=logs --host 0.0.0.0 --port 6006
